name: C CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make -s

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test -s

